### ISSUE TITLE
Add protocol fees in the withdraw function

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#1034]
## Rationale

Make it possible to charge protocol fees at withdrawal time. See https://github.com/sablier-labs/company-discussions/discussions/72.

There are two big advantages for charging fees at withdrawal time compared to deposit:

- Incentivizes us to pursue more integrations for Lockup
- Solves the nasty issues associated with airstreams campaign

## Spec

Note: this is similar to the historical functionality that used to be available in v1.1.0 and below, however, for simplicity purposes, this newer spec does not include a Comptroller.

- [ ] Add `getProtocolFee` getter
- [ ] Add `_protocolFees` mapping
- [ ] Add `setProtocolFee` setter gated by admin function
- [ ] When the protocol fee is not zero, charge a fee from the withdrawn amount

**Comment by PaulRBerg** [comment]
Discarding feature this as per the discussion [here](https://github.com/sablier-labs/company-discussions/discussions/72#discussioncomment-11154982).
