### ISSUE TITLE
LockupTranched: a new Lockup contract with sharply delineated chunks

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#787]
As discussed here: https://github.com/sablier-labs/company-discussions/discussions/19

Tasks:

- [x] Build a PoC implementation
- [x] Benchmark the PoC against `LockupDynamic`:
    - Compare the creation of Unlock in Steps streams, e.g. [this](https://docs.sablier.com/concepts/protocol/stream-types#unlock-in-steps)
    - Compare withdrawals from standard streams with one segment, i.e., how much more gas efficient will the `withdraw` function in `LockupTranched` be
- [x] Decide if `LockupTranched` is worth it
- [ ] Proceed with writing tests for it (using [Bulloak](https://github.com/alexfertel/bulloak))

Note: we will keep using the same terminology, i.e., `streams` and `streamedAmountOf`. Related: https://github.com/sablier-labs/v2-core/discussions/708#discussioncomment-8082942

**Comment by andreivladbrg** [comment]
Just wanted to let you know that I've implemented the POC and did benchmarks (see `README` file). You can see the work here:
https://github.com/andreivladbrg/v2-tranched/

Now it is up to decide if it worth implementing here.

**Comment by PaulRBerg** [comment]
Awesome, thanks @andreivladbrg, will review later.

**Comment by PaulRBerg** [comment]
Kudos, @andreivladbrg, for the benchmark you have prepared [here](https://github.com/andreivladbrg/v2-tranched).

I think it is as clear as day that we should move forward with `LockupTranched`

- For 2-year vesting, it saves (i) up to 300K gas at creation time and (ii) up to 20k gas per withdrawal
- For 2-year vesting, it saves (i) up to 600K gas at creation time and (ii) up to 25k gas per withdrawal
- For 4-year vesting, it saves (i) up to 1.2M gas at creation time and (ii) up to 36k gas per withdrawal

These gas optimizations are due to LT making it possible to have half as many segments as LD. But LT is more efficient even when the number of segments is equal.

<img width="500" alt="Screenshot 2024-01-23 at 11 14 33 AM" src="https://github.com/sablier-labs/v2-core/assets/8782666/1a0ae6d9-3967-4e30-8fea-0db7a3e91569">

@razgraf could you give us the green light?

**Comment by razgraf** [comment]
Sounds good!

**Comment by PaulRBerg** [comment]
Great, thanks.

@andreivladbrg, you can move forward with implementing `LockupTranched` properly. The contract should be added in V2 Core.

Note: we should first merge https://github.com/sablier-labs/v2-core/pull/798

**Comment by andreivladbrg** [comment]
> @andreivladbrg, you can move forward with implementing LockupTranched properly. The contract should be added in V2 Core.

I will, but currently I am working on making a huge refactor for core, that it would be very beneficial as the `Lockup` contracts are increasing

https://github.com/andreivladbrg/refactor-core/

saying it now, it may take a while

**Comment by PaulRBerg** [comment]
That's fine but please create a discussion/ proposal prior to a PR

**Comment by andreivladbrg** [comment]
https://github.com/sablier-labs/v2-core/commit/34fee6bc128f2219538056cdf920ccb12e84945c
